# Generated by Django 3.1.7 on 2021-05-03 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_task_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('B', 'Baixa'), ('M', 'Média'), ('A', 'Alta'), ('S', 'SuperAlta')], max_length=1, verbose_name='Prioridade'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('EX', 'Em execução'), ('PD', 'Pendente'), ('CD', 'Concluída')], max_length=2, verbose_name='Status'),
        ),
    ]
